### ISSUE TITLE
Operator[SoftmaxCrossEntropyWithLogits] is not support.

### ISSUE THREAD

**Issue by mathslimin** [mindspore-ai/mindarmour#2]
### Hardware Environment(`Ascend`/`GPU`/`CPU`): 
> Uncomment only one ` /device <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> `/device cpu`</br>

### Software Environment:
- **MindSpore version (source or binary)**:binary
- **Python version (e.g., Python 3.7.5)**:python3.7.5
- **OS platform and distribution (e.g., Linux Ubuntu 16.04)**:ubuntu 18.04
- **GCC/Compiler version (if compiled from source)**: 

## Describe the current behavior

mnist_attack_fgsm crash
## Steps to reproduce the issue
1. python3.7 mnist_attack_fgsm.py

## Related log / screenshot

mnist_attack_fgsm.py:87: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  start_time = time.clock()
[ERROR] ME(3438,python):2020-05-07-23:11:49.929.959 [mindspore/ccsrc/device/cpu/cpu_session.cc:115] BuildKernel] Operator[SoftmaxCrossEntropyWithLogits] is not support.
Traceback (most recent call last):
  File "mnist_attack_fgsm.py", line 119, in <module>
    test_fast_gradient_sign_method()
  File "mnist_attack_fgsm.py", line 89, in test_fast_gradient_sign_method
    np.concatenate(test_labels), batch_size=32)
  File "/usr/local/lib/python3.7/dist-packages/mindarmour-0.2.0-py3.7.egg/mindarmour/attacks/attack.py", line 65, in batch_generate
    adv_x = self.generate(x_batch, y_batch)
  File "/usr/local/lib/python3.7/dist-packages/mindarmour-0.2.0-py3.7.egg/mindarmour/attacks/gradient_method.py", line 96, in generate
    gradient = self._gradient(inputs, labels)
  File "/usr/local/lib/python3.7/dist-packages/mindarmour-0.2.0-py3.7.egg/mindarmour/attacks/gradient_method.py", line 290, in _gradient
    out_grad = self._grad_all(Tensor(inputs), Tensor(labels), sens)
  File "/usr/local/lib/python3.7/dist-packages/mindspore/nn/cell.py", line 147, in __call__
    out = self.compile_and_run(*inputs)
  File "/usr/local/lib/python3.7/dist-packages/mindspore/nn/cell.py", line 301, in compile_and_run
    _, compile_flag = _executor.compile(self, *inputs, phase=self.phase)
  File "/usr/local/lib/python3.7/dist-packages/mindspore/common/api.py", line 363, in compile
    result = self._executor.compile(obj, args_list, phase, use_vm)
RuntimeError: mindspore/ccsrc/device/cpu/cpu_session.cc:115 BuildKernel] Operator[SoftmaxCrossEntropyWithLogits] is not support.

**Comment by jinxiulang** [comment]
Thanks for your issue.
In fact, there are two optional modes for Operator[SoftmaxCrossEntropyWithLogits]: sparse=False(which means input labels are one-hot style) and sparse=True(which means labels are sparse style).
Furthermore, sparse=False is the default mode, while mindspore-cpu do only supports sparse=True until now. 
Hence, you can use SoftmaxCrossEntropyWithLogits(is_grad=False, sparse=True) as a substitute.
By the way, a fast gradient attack example for mindspore-cpu is provided in mindarmour/tests/ut/python/attacks/test_gradient_method.py(line106).
Enjoy it!
